In [0]:
import numpy as np  #we can replace np with any name

In [2]:
x = [1,2,3,4,5,6]
np_x = np.array(x)
np_x

array([1, 2, 3, 4, 5, 6])

In [3]:
# get shape
np_x.shape

(6,)

In [4]:
# type
# It will follow PC, if PC is 64bit, automatically will be int64
np_x.dtype

dtype('int64')

In [5]:
np_x[0] # indexing, reassign

1

In [6]:
np_x[0] = 1.12131 # dilute
np_x

array([1, 2, 3, 4, 5, 6])

In [7]:
np_x_float = np_x.astype(np.float64)
np_x_float

array([1., 2., 3., 4., 5., 6.])

In [8]:
np_x_float[0] = 1.12131
np_x_float

array([1.12131, 2.     , 3.     , 4.     , 5.     , 6.     ])

## reshaping

In [26]:
x = np.arange(100)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [25]:
y = np.arange(0,100,2)
y

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [21]:
x_2d = np.reshape(x, (50, -1)) #-1 can be replaced by any negative number
x_2d.shape                     # so let say from 0 to 100, divide by 50, will be 2, so 2 will replace the -1

(50, 1)

In [33]:
np.reshape(x, (10, 7, -1)).shape

ValueError: ignored

In [30]:
np.reshape(x, (10, 2, 5)).shape

(10, 2, 5)

In [34]:
np.reshape(x, (10, 2, 5, 1, 1, 1, 1, 1)).shape

(10, 2, 5, 1, 1, 1, 1, 1)

## Concatenate

In [0]:
x = np.arange(20)
y = np.arange(20)
x_2d = np.reshape(x, (10, 2))
y_2d = np.reshape(y, (10, 2))

In [36]:
x_2d.shape, y_2d.shape

((10, 2), (10, 2))

In [37]:
np.concatenate([x_2d,y_2d], axis=1).shape

(10, 4)

In [38]:
np.concatenate([x_2d,y_2d], axis=1)

array([[ 0,  1,  0,  1],
       [ 2,  3,  2,  3],
       [ 4,  5,  4,  5],
       [ 6,  7,  6,  7],
       [ 8,  9,  8,  9],
       [10, 11, 10, 11],
       [12, 13, 12, 13],
       [14, 15, 14, 15],
       [16, 17, 16, 17],
       [18, 19, 18, 19]])

In [39]:
np.concatenate([x_2d,y_2d], axis=0).shape

(20, 2)

In [40]:
np.concatenate([x_2d,y_2d], axis=0)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [0]:
#small example
x = np.arange(5)
y = np.arange(5,10)
x_2d = np.reshape(x, (5, 1))
y_2d = np.reshape(y, (5, 1))

In [42]:
x_2d

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [43]:
y_2d

array([[5],
       [6],
       [7],
       [8],
       [9]])

In [44]:
np.concatenate([x_2d,y_2d], axis=1) #combine at column 1

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [45]:
np.concatenate([x_2d,y_2d], axis=0)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [46]:
np.concatenate([x_2d,y_2d], axis=0).shape

(10, 1)

In [47]:
np.concatenate([x_2d, y_2d], axis = 2) # error, axis not exist

AxisError: ignored

## Slicing

In [0]:
x = np.arange(100)
x_2d = np.reshape(x,(10,10))

In [49]:
# i want from second row until second last row (not included)
# i want from fourth last column until last column (not included)
x_2d[1: -2, -4: -1].shape

(7, 3)

## Combine everything

In [0]:
x = np.arange(1000)
y = np.arange(2000)

In [0]:
# 1. i want to reshape x become (10, 5, 10, 2)
# 2. i want to reshape y become (10, 5, 10, -1)
x_reshape = np.reshape(x, (10, 5, 10, 2))
y_reshape = np.reshape(y, (10, 5, 10, -1))

In [0]:
# 3. combine both reshaped on last axis
concat = np.concatenate([x_reshape, y_reshape], axis = -1)

In [54]:
concat

array([[[[   0,    1,    0,    1,    2,    3],
         [   2,    3,    4,    5,    6,    7],
         [   4,    5,    8,    9,   10,   11],
         ...,
         [  14,   15,   28,   29,   30,   31],
         [  16,   17,   32,   33,   34,   35],
         [  18,   19,   36,   37,   38,   39]],

        [[  20,   21,   40,   41,   42,   43],
         [  22,   23,   44,   45,   46,   47],
         [  24,   25,   48,   49,   50,   51],
         ...,
         [  34,   35,   68,   69,   70,   71],
         [  36,   37,   72,   73,   74,   75],
         [  38,   39,   76,   77,   78,   79]],

        [[  40,   41,   80,   81,   82,   83],
         [  42,   43,   84,   85,   86,   87],
         [  44,   45,   88,   89,   90,   91],
         ...,
         [  54,   55,  108,  109,  110,  111],
         [  56,   57,  112,  113,  114,  115],
         [  58,   59,  116,  117,  118,  119]],

        [[  60,   61,  120,  121,  122,  123],
         [  62,   63,  124,  125,  126,  127],
         [  

In [55]:
concat.shape

(10, 5, 10, 6)

In [56]:
# 4. i want from second until fifth rows (not included)
# i want from first until second last column (not included)
# i want from third until third last depth (not included)
# i want from first until first last a-axis (not included)

concat[1: 4, 0:-2, 2: -3, 0: -1].shape

(3, 3, 5, 5)

In [57]:
concat[1: 4, 0:-2, 2: -3, 0: -1]

array([[[[104, 105, 208, 209, 210],
         [106, 107, 212, 213, 214],
         [108, 109, 216, 217, 218],
         [110, 111, 220, 221, 222],
         [112, 113, 224, 225, 226]],

        [[124, 125, 248, 249, 250],
         [126, 127, 252, 253, 254],
         [128, 129, 256, 257, 258],
         [130, 131, 260, 261, 262],
         [132, 133, 264, 265, 266]],

        [[144, 145, 288, 289, 290],
         [146, 147, 292, 293, 294],
         [148, 149, 296, 297, 298],
         [150, 151, 300, 301, 302],
         [152, 153, 304, 305, 306]]],


       [[[204, 205, 408, 409, 410],
         [206, 207, 412, 413, 414],
         [208, 209, 416, 417, 418],
         [210, 211, 420, 421, 422],
         [212, 213, 424, 425, 426]],

        [[224, 225, 448, 449, 450],
         [226, 227, 452, 453, 454],
         [228, 229, 456, 457, 458],
         [230, 231, 460, 461, 462],
         [232, 233, 464, 465, 466]],

        [[244, 245, 488, 489, 490],
         [246, 247, 492, 493, 494],
         [248, 2